{
    "train_micro_batch_size_per_gpu":8,
    "train_batch_size": "auto",
    "gradient_accumulation_steps": 16,
    "optimizer": {
      "type": "ZeroOneAdam",
      "params": {
        "lr": 1e-5,
        "weight_decay": 0.01,
        "bias_correction": false,
        "var_freeze_step": 1000,
        "var_update_scaler": 16,
        "local_step_scaler": 1000,
        "local_step_clipper": 16,
        "cuda_aware": false,
        "comm_backend_name": "mpi"
        }
      
      },
     "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 1e-5,
            "warmup_num_steps": 10000
        }
    },
    "bf16": {
      "enabled": true
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer":{
            "device":"cpu",
            "pin_memory":true
        },
        "allgather_partitions":true,
        "allgather_bucket_size":2e8,
        "overlap_comm":true,
        "reduce_sactter":true,
        "reduce_bucket_size":2e8,
        "contiguous_gradients":true
    }
  }